### ISSUE TITLE
Update checklist in appendix

### ISSUE THREAD

**Issue by YesCT** [Lullabot/information-security-policy#266]
- [ ] Create a new branch
- [ ] For new pages, nest it under the appropriate category page and add the page to SUMMARY.md
- [ ] Update the ISO 27000 cross-reference in the appendix to indicate which section(s) of ISO 27000 this item refers to.
- [ ] Create a PR with the handbook changes and link it to this issue.
- [ ] Review the PR with the security team

https://security.lullabot.com/appendix/device-checklist.html

Make consistent with https://docs.google.com/spreadsheets/d/1vixR2xJ3Y-EgqBg-x9x3RhK1wdUA0AJntGRCbuKfnAE/edit?gid=410995281#gid=410995281 (where appropriate, maybe some places we don't update the checklist webpage, but we change the spreadsheet for 2025).
